CREATE DATABASE IF NOT EXISTS kairos;
USE kairos;

CREATE TABLE IF NOT EXISTS students (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  college VARCHAR(150) NOT NULL,
  course VARCHAR(100) NOT NULL,
  availability VARCHAR(50),
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recruiters (
  recruiter_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  company_name VARCHAR(150) NOT NULL,
  job_title VARCHAR(100) NOT NULL,
  industry VARCHAR(50),
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS jobs (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  recruiter_id INT UNSIGNED NOT NULL,
  title VARCHAR(150) NOT NULL,
  work_type ENUM('On-site', 'Hybrid', 'Remote') NOT NULL,
  location VARCHAR(150) NOT NULL,
  hours VARCHAR(30) NOT NULL,
  pay VARCHAR(80) NOT NULL,
  vacancies TINYINT UNSIGNED NOT NULL DEFAULT 1,
  description VARCHAR(300) NOT NULL,
  status ENUM('Active', 'Paused') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (recruiter_id) REFERENCES recruiters(recruiter_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS saved_jobs (
  student_id INT UNSIGNED NOT NULL,
  job_id INT UNSIGNED NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (student_id, job_id),
  FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
);
